/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cloud_logic_custom": [
        {
            "name": "pythonapi",
            "endpoint": "https://kc76udpiz5.execute-api.eu-west-1.amazonaws.com/staging",
            "region": "eu-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-1:f5d52403-1c64-4861-8728-c0c4f2fadaa2",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_1um1iujgu",
    "aws_user_pools_web_client_id": "66e7mf5o6cvh1ci0ev0bp2e5cg",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "sanja-web-files",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
