/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cloud_logic_custom": [
        {
            "name": "pythonapi",
            "endpoint": "https://xs4p80dihg.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-1:375da9ac-2f19-4cd9-888d-0ec478209213",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_XWKqbDLZs",
    "aws_user_pools_web_client_id": "4grt9m7js86e3jt1rejkkj7h",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "sanja-web-files",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
